// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcvurawwvojdzssddmlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjdnVyYXd3dm9qZHpzc2RkbWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODI2MTMsImV4cCI6MjA3MDU1ODYxM30.UWIOJi9OEi-GS9W-5UuFQTT3Q3BxXCwqxCLW9PTih9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});